run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - govet          # Official Go vet tool
    - errcheck       # Check for unchecked errors
    - staticcheck    # Static analysis
    - gosimple       # Suggest code simplifications
    - ineffassign    # Detect ineffectual assignments
    - unused         # Check for unused constants, variables, functions
    - gofmt          # Check code formatting
    - goimports      # Check import ordering
    - misspell       # Check for misspelled words
    - gocritic       # Go code review
    - revive         # Fast and configurable linter

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true

  errcheck:
    check-blank: true
    check-type-assertions: true

  goimports:
    local-prefixes: github.com/mickeyleetw/grid-trading-bot

  revive:
    rules:
      - name: error-return
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments

issues:
  exclude-rules:
    # Exclude certain linters for test files
    - path: _test\.go
      linters:
        - errcheck
        - gocritic

    # Exclude common false positives
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

  max-same-issues: 0
  max-issues-per-linter: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
